trigger:
  branches:
    include:
      - master

pool: 
  name: Azure Pipelines 
  vmImage: 'ubuntu-latest'

variables:
  major: 0
  minor: $[counter(variables['major'], 0)]
  tag: v$(major).$(minor).$(Build.BuildId)

stages:
  - template: ./quality_gates.yaml
    parameters:
      sonarCloudServiceConnection: 'acelensonarcloud-${{values.azureDevOpsProject}}'
  - template: ./build.yaml
    parameters:
      tag: $(tag)
  - template: ./semver.yaml
    parameters:
      tag: $(tag)
