parameters:
  - name: tag
    type: string

stages: 
  # update the image in the gitops repository in file values.yaml (backstage.image)
  - stage: semanticVersioning
    displayName: Semantic Versioning
    jobs:
      - job: tagCommit
        displayName: Tag Commit

        steps:
        - checkout: self
          persistCredentials: true

        - script: |
            echo "Tagging the commit with the tag ${{parameters.tag}}"
            git tag ${{parameters.tag}}
            git push origin ${{parameters.tag}}