"""Add new fields to city and create country and state models

Revision ID: 3
Revises: 2
Create Date: 2024-04-21 21:03:57.841551

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3"
down_revision = "2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "country_id", name="_state_country_uc"),
    )
    op.create_index(op.f("ix_states_id"), "states", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_states_id"), table_name="states")
    op.drop_table("states")
    # ### end Alembic commands ###
