"""Add new fields to city and create country and state models

Revision ID: 4
Revises: 3
Create Date: 2024-04-21 21:09:05.802695

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4"
down_revision = "3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cities", sa.Column("state_province_id", sa.Integer(), nullable=True))
    op.add_column("cities", sa.Column("country_id", sa.Integer(), nullable=True))
    op.add_column("cities", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("cities", sa.Column("longitude", sa.Float(), nullable=True))
    op.create_foreign_key(None, "cities", "states", ["state_province_id"], ["id"])
    op.create_foreign_key(None, "cities", "countries", ["country_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cities", type_="foreignkey")
    op.drop_constraint(None, "cities", type_="foreignkey")
    op.drop_column("cities", "longitude")
    op.drop_column("cities", "latitude")
    op.drop_column("cities", "country_id")
    op.drop_column("cities", "state_province_id")
    # ### end Alembic commands ###
