"""Add new fields to city and create country and state models

Revision ID: 5
Revises: 4
Create Date: 2024-04-21 21:09:05.802695

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5"
down_revision = "4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("FK__cities__country___3F466844", "cities", type_="foreignkey")
    op.drop_column("cities", "country_id")
    op.drop_column("cities", "longitude")
    op.drop_column("cities", "latitude")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "cities", "countries", ["country_id"], ["id"])
    op.add_column("cities", sa.Column("country_id", sa.Integer(), nullable=True))
    op.add_column("cities", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("cities", sa.Column("longitude", sa.Float(), nullable=True))
    # ### end Alembic commands ###
